language: node_js
node_js:
  - "8.4"
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - nvm install 8.4
  - yarn install
  # # Install SDK license so Android Gradle plugin can install deps.
  # - mkdir "$ANDROID_HOME/licenses" || true
  # - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # # Install the rest of tools (e.g. avdmanager)
  # - sdkmanager tools
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      env:
        - REACT_NATIVE_VERSION=0.55.3
      android:
        components:
          - build-tools-27.0.3
          - build-tools-26.0.2
          - android-27
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - sys-img-armeabi-v7a-android-27
      install:
        - android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-27
        - android list targets
        - android create avd --force -n test -t android-27 --abi armeabi-v7a
      script:
        # Install the system image.
        # - sdkmanager "system-images;android-27;default;armeabi-v7a"
        # # Create and start emulator for the script. Meant to race the install task.
        # - echo no | avdmanager create avd --force -n test -k "system-images;android-27;default;armeabi-v7a"
        # - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
        # # Build apk
        - cd android && ./gradlew assembleRelease && cd ..
        # fix detox
        - npm rebuild detox
        - ./node_modules/.bin/detox build --configuration android.emu.debug
        - adb wait-for-device
        - ./node_modules/.bin/detox test --configuration android.emu.debug
