language: node_js
node_js:
  - "8.4"
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - nvm install 8.4
  - yarn install
  - echo no | avdmanager create avd -f -n test -k 'system-images;android-27;google_apis;armeabi-v7a'
  - emulator -avd test -no-audio -no-window &
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      env:
        - REACT_NATIVE_VERSION=0.55.3
      android:
        components:
          - build-tools-27.0.3
          - build-tools-26.0.2
          - android-27
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - sys-img-armeabi-v7a-android-27
      script:
        - cd android && ./gradlew assembleRelease && cd ..
        - npm rebuild detox
        - ./node_modules/.bin/detox build --configuration android.emu.debug
        - adb wait-for-device
        - ./node_modules/.bin/detox test --configuration android.emu.debug
