language: node_js
node_js:
  - "8.4"
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - nvm install 8.4
  - yarn install
  # fix detox
  - npm rebuild detox
  # # Install SDK license so Android Gradle plugin can install deps.
  # - mkdir "$ANDROID_HOME/licenses" || true
  # - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # # Install the rest of tools (e.g. avdmanager)
  # - sdkmanager tools
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      env:
        - REACT_NATIVE_VERSION=0.55.3
      android:
        components:
          - build-tools-27.0.3
          - build-tools-26.0.2
          - android-27
          - android-19
          - extra-google-simulators
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - sys-img-x86-google_apis-19
      install:
        - android list targets
        - echo no | android create avd --force -n test -t android-19 --abi google_apis/x86
      script:
        # Install the system image.
        # - sdkmanager "system-images;android-27;default;armeabi-v7a"
        # # Create and start emulator for the script. Meant to race the install task.
        # - echo no | avdmanager create avd --force -n test -k "system-images;android-27;default;armeabi-v7a"
        - emulator -verbose -avd test -no-audio -no-window -accel on -engine qemu2 &
        # # Build apk
        - cd android && ./gradlew assembleRelease && cd ..
        # build detox
        - ./node_modules/.bin/detox build --configuration android.emu.debug
        # wait for emulator to boot
        - emulator -avd test -no-audio -no-window &
        - adb kill-server
        - adb start-server
        - adb reconnect device
        - adb reconnect
        - adb wait-for-device
        # run e2e tests
        - ./node_modules/.bin/detox test --configuration android.emu.debug
