language: node_js
node_js:
  - "8.4"
sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - yarn install
  - npm rebuild detox
  - npm run test:detox:android
